spring:
  application:
    name: vsquare-audit
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_details  
    username: postgres_user
    password: password
  jpa: 
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
          
server:
  port: 8181
  
 
